## Experiment 2: Random Forest Classifier

In [11]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

In [3]:
data_df = pd.read_csv('../data/cleaned/South_East_Asia_Social_Media_MentalHealth_cleaned.csv')

In [5]:
X = data_df[['Daily SM Usage (hrs)', 'Peer Comparison Frequency (1-10)', 'Cyberbullying Experience (1-10)']]
y = data_df['Self Confidence Impact (1-10)'] 

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions
y_pred = rf_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.09907016308811452
[[704 674 622 691 704 712 731 698 679 673]
 [686 697 676 633 702 661 666 731 669 725]
 [652 694 659 711 706 682 707 671 714 695]
 [676 713 682 672 661 643 661 659 746 633]
 [714 715 724 728 687 649 657 705 673 684]
 [686 721 658 693 664 646 705 681 638 700]
 [675 701 657 647 701 692 693 693 687 636]
 [635 719 647 703 700 674 706 675 714 670]
 [715 669 617 681 689 658 661 675 642 674]
 [666 692 669 652 675 673 678 689 705 680]]
              precision    recall  f1-score   support

           1       0.10      0.10      0.10      6888
           2       0.10      0.10      0.10      6846
           3       0.10      0.10      0.10      6891
           4       0.10      0.10      0.10      6746
           5       0.10      0.10      0.10      6936
           6       0.10      0.10      0.10      6792
           7       0.10      0.10      0.10      6782
           8       0.10      0.10      0.10      6843
           9       0.09      0.10      0.09      668

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Initialize the model
mlp_model = MLPClassifier(hidden_layer_sizes=(100), max_iter=500, random_state=42)

# Train the model
mlp_model.fit(X_train, y_train)

# Make predictions
y_pred = mlp_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy}")
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.09939281942977825
[[  27    0    0  168    5    0 4412 2237    0   39]
 [  32    0    0  167    4    0 4404 2208    0   31]
 [  26    0    0  150    2    0 4510 2162    0   41]
 [  40    0    0  183    2    0 4385 2104    0   32]
 [  36    0    0  174    8    0 4482 2201    0   35]
 [  32    0    0  167    4    0 4384 2181    0   24]
 [  25    0    0  160    3    0 4384 2179    0   31]
 [  35    0    0  166    5    0 4452 2140    0   45]
 [  31    0    0  143    5    0 4371 2086    0   45]
 [  26    0    0  170    4    0 4445 2099    0   35]]
              precision    recall  f1-score   support

           1       0.09      0.00      0.01      6888
           2       0.00      0.00      0.00      6846
           3       0.00      0.00      0.00      6891
           4       0.11      0.03      0.04      6746
           5       0.19      0.00      0.00      6936
           6       0.00      0.00      0.00      6792
           7       0.10      0.65      0.17      6782
      

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  